# Generated by Django 5.0.6 on 2024-07-07 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPolicialRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CuartoGuardiaRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuarto', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ComisariaTerceraRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.codigopolicialrg')),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.cuartoguardiarg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaSegundaRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.codigopolicialrg')),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.cuartoguardiarg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaQuintaRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.codigopolicialrg')),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.cuartoguardiarg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaPrimeraRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.codigopolicialrg')),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.cuartoguardiarg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaCuartaRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.codigopolicialrg')),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisariasriogrande.cuartoguardiarg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
