# Generated by Django 5.0.6 on 2024-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisariasriogrande', '0001_initial'),
        ('compartido', '0002_codigopolicialrg_codigossecundariosrg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisariacuartarg',
            name='codigos_secundarios',
        ),
        migrations.RemoveField(
            model_name='comisariaprimerarg',
            name='codigos_secundarios',
        ),
        migrations.RemoveField(
            model_name='comisariaquintarg',
            name='codigos_secundarios',
        ),
        migrations.RemoveField(
            model_name='comisariasegundarg',
            name='codigos_secundarios',
        ),
        migrations.RemoveField(
            model_name='comisariatercerarg',
            name='codigos_secundarios',
        ),
        migrations.AddField(
            model_name='comisariacuartarg',
            name='codigos_secundariosRG',
            field=models.ManyToManyField(blank=True, to='compartido.codigossecundariosrg'),
        ),
        migrations.AddField(
            model_name='comisariaprimerarg',
            name='codigos_secundariosRG',
            field=models.ManyToManyField(blank=True, to='compartido.codigossecundariosrg'),
        ),
        migrations.AddField(
            model_name='comisariaquintarg',
            name='codigos_secundariosRG',
            field=models.ManyToManyField(blank=True, to='compartido.codigossecundariosrg'),
        ),
        migrations.AddField(
            model_name='comisariasegundarg',
            name='codigos_secundariosRG',
            field=models.ManyToManyField(blank=True, to='compartido.codigossecundariosrg'),
        ),
        migrations.AddField(
            model_name='comisariatercerarg',
            name='codigos_secundariosRG',
            field=models.ManyToManyField(blank=True, to='compartido.codigossecundariosrg'),
        ),
    ]
