# Generated by Django 5.0.6 on 2024-07-27 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPolicialUSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CuartoGuardiaUSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuarto', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ComisariaTercera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('movil_patrulla', models.CharField(blank=True, max_length=255, null=True)),
                ('a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('secundante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instituciones_intervinientes', models.TextField(blank=True, null=True)),
                ('tareas_judiciales', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_tercera_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_tercera_updated_records', to=settings.AUTH_USER_MODEL)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisarias.cuartoguardiaush')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaSegunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('movil_patrulla', models.CharField(blank=True, max_length=255, null=True)),
                ('a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('secundante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instituciones_intervinientes', models.TextField(blank=True, null=True)),
                ('tareas_judiciales', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_segunda_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_segunda_updated_records', to=settings.AUTH_USER_MODEL)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisarias.cuartoguardiaush')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaQuinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('movil_patrulla', models.CharField(blank=True, max_length=255, null=True)),
                ('a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('secundante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instituciones_intervinientes', models.TextField(blank=True, null=True)),
                ('tareas_judiciales', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_quinta_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_quinta_updated_records', to=settings.AUTH_USER_MODEL)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisarias.cuartoguardiaush')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaPrimera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('movil_patrulla', models.CharField(blank=True, max_length=255, null=True)),
                ('a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('secundante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instituciones_intervinientes', models.TextField(blank=True, null=True)),
                ('tareas_judiciales', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_primera_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_primera_updated_records', to=settings.AUTH_USER_MODEL)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisarias.cuartoguardiaush')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaCuarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('movil_patrulla', models.CharField(blank=True, max_length=255, null=True)),
                ('a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('secundante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instituciones_intervinientes', models.TextField(blank=True, null=True)),
                ('tareas_judiciales', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_cuarta_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisaria_cuarta_updated_records', to=settings.AUTH_USER_MODEL)),
                ('cuarto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comisarias.cuartoguardiaush')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
