# Generated by Django 5.0.6 on 2024-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComisariaCuarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaPrimera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaQuinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaSegunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComisariaTercera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('a_cargo', models.CharField(max_length=255)),
                ('secundante', models.CharField(max_length=255)),
                ('nombre_victima', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('trabajo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
