# Generated by Django 5.0.6 on 2024-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
