# Generated by Django 5.0.6 on 2024-08-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='resolucion',
        ),
        migrations.AddField(
            model_name='resolucioncodigo',
            name='comisaria_cuarta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='comisarias.comisariacuarta'),
        ),
        migrations.AddField(
            model_name='resolucioncodigo',
            name='comisaria_primera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='comisarias.comisariaprimera'),
        ),
        migrations.AddField(
            model_name='resolucioncodigo',
            name='comisaria_quinta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='comisarias.comisariaquinta'),
        ),
        migrations.AddField(
            model_name='resolucioncodigo',
            name='comisaria_segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='comisarias.comisariasegunda'),
        ),
        migrations.AddField(
            model_name='resolucioncodigo',
            name='comisaria_tercera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='comisarias.comisariatercera'),
        ),
    ]
