# Generated by Django 5.0.6 on 2024-06-21 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
