# Generated by Django 5.0.6 on 2024-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosSecundarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, to='comisarias.codigossecundarios'),
        ),
    ]
