# Generated by Django 5.0.6 on 2024-08-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0002_remove_comisariacuarta_resolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='firmas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='firmas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='firmas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='firmas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='firmas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
