# Generated by Django 5.0.6 on 2024-08-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0002_codigossecundarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigossecundarios',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
