# Generated by Django 5.0.6 on 2024-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0002_uploadedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to='partespdf/'),
        ),
    ]
