# Generated by Django 5.0.6 on 2024-07-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0003_codigopolicial_cuartoguardia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodigoPolicial',
            new_name='CodigoPolicialUSH',
        ),
        migrations.RenameModel(
            old_name='CuartoGuardia',
            new_name='CuartoGuardiaUSH',
        ),
    ]
