# Generated by Django 5.0.6 on 2024-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0003_alter_codigossecundarios_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopolicialush',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
