# Generated by Django 5.0.6 on 2024-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0003_comisariacuarta_firmas_comisariaprimera_firmas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisariacuarta',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='comisarias.codigossecundarios'),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='codigos_secundarios',
            field=models.ManyToManyField(blank=True, null=True, to='comisarias.codigossecundarios'),
        ),
    ]
