# Generated by Django 5.0.6 on 2024-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0004_alter_codigopolicialush_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='resolucion_codigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='resolucion_codigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='resolucion_codigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='resolucion_codigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='resolucion_codigo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
