# Generated by Django 5.0.6 on 2024-09-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0004_codigopolicialush_nombre_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionesFederales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInstitucionFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movil_federal', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_a_cargo_federal', models.CharField(blank=True, max_length=255, null=True)),
                ('comisaria_cuarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_federal', to='comisarias.comisariacuarta')),
                ('comisaria_primera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_federal', to='comisarias.comisariaprimera')),
                ('comisaria_quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_federal', to='comisarias.comisariaquinta')),
                ('comisaria_segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_federal', to='comisarias.comisariasegunda')),
                ('comisaria_tercera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_federal', to='comisarias.comisariatercera')),
                ('institucion_federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisarias.institucionesfederales')),
            ],
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='instituciones_federales',
            field=models.ManyToManyField(blank=True, to='comisarias.institucionesfederales'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='instituciones_federales',
            field=models.ManyToManyField(blank=True, to='comisarias.institucionesfederales'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='instituciones_federales',
            field=models.ManyToManyField(blank=True, to='comisarias.institucionesfederales'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='instituciones_federales',
            field=models.ManyToManyField(blank=True, to='comisarias.institucionesfederales'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='instituciones_federales',
            field=models.ManyToManyField(blank=True, to='comisarias.institucionesfederales'),
        ),
    ]
