# Generated by Django 5.0.6 on 2024-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0005_alter_comisariacuarta_codigos_secundarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciasSecundarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='dependencias_secundarias',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciassecundarias'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='dependencias_secundarias',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciassecundarias'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='dependencias_secundarias',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciassecundarias'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='dependencias_secundarias',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciassecundarias'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='dependencias_secundarias',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciassecundarias'),
        ),
    ]
