# Generated by Django 5.0.6 on 2024-07-22 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0005_remove_comisariacuarta_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='nombre_victima',
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='nombre_victima',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='nombre_victima',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='nombre_victima',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='nombre_victima',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='instituciones_intervinientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='lugar_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='tareas_judiciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='instituciones_intervinientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='lugar_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='tareas_judiciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='instituciones_intervinientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='lugar_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='tareas_judiciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='instituciones_intervinientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='lugar_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='tareas_judiciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='instituciones_intervinientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='lugar_codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='tareas_judiciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comisariacuarta',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comisariacuarta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comisariaprimera',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comisariaquinta',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comisariasegunda',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comisariatercera',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.codigopolicialush'),
        ),
    ]
