# Generated by Django 5.0.6 on 2024-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0006_dependenciassecundarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
