# Generated by Django 5.0.6 on 2024-09-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0006_rename_dependencias_secundarias_comisariacuarta_dependendencias_secundarias_and_more'),
        ('compartido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisariaprimera',
            name='cuarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.AlterField(
            model_name='comisariacuarta',
            name='cuarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='cuarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='cuarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='cuarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.AddField(
            model_name='codigopolicialush',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codigossecundarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dependenciasmunicipales',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dependenciasprovinciales',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dependenciassecundarias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institucionesfederales',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institucioneshospitalarias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviciosemergencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitantecodigo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CuartoGuardiaUSH',
        ),
    ]
