# Generated by Django 5.0.6 on 2024-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0006_remove_comisariacuarta_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisariacuarta',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
