# Generated by Django 5.0.6 on 2024-08-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0007_comisariacuarta_latitude_comisariacuarta_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciasMunicipales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DependenciasProvinciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionesHospitalarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitanteCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='dependencias_municipales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasmunicipales'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='dependencias_municipales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasmunicipales'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='dependencias_municipales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasmunicipales'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='dependencias_municipales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasmunicipales'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='dependencias_municipales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasmunicipales'),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='dependencias_provinciales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasprovinciales'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='dependencias_provinciales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasprovinciales'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='dependencias_provinciales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasprovinciales'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='dependencias_provinciales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasprovinciales'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='dependencias_provinciales',
            field=models.ManyToManyField(blank=True, to='comisarias.dependenciasprovinciales'),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='instituciones_hospitalarias',
            field=models.ManyToManyField(blank=True, to='comisarias.institucioneshospitalarias'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='instituciones_hospitalarias',
            field=models.ManyToManyField(blank=True, to='comisarias.institucioneshospitalarias'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='instituciones_hospitalarias',
            field=models.ManyToManyField(blank=True, to='comisarias.institucioneshospitalarias'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='instituciones_hospitalarias',
            field=models.ManyToManyField(blank=True, to='comisarias.institucioneshospitalarias'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='instituciones_hospitalarias',
            field=models.ManyToManyField(blank=True, to='comisarias.institucioneshospitalarias'),
        ),
        migrations.CreateModel(
            name='DetalleServicioEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_a_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('comisaria_cuarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio_emergencia', to='comisarias.comisariacuarta')),
                ('comisaria_primera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio_emergencia', to='comisarias.comisariaprimera')),
                ('comisaria_quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio_emergencia', to='comisarias.comisariaquinta')),
                ('comisaria_segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio_emergencia', to='comisarias.comisariasegunda')),
                ('comisaria_tercera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio_emergencia', to='comisarias.comisariatercera')),
                ('servicio_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisarias.serviciosemergencia')),
            ],
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, to='comisarias.serviciosemergencia'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, to='comisarias.serviciosemergencia'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, to='comisarias.serviciosemergencia'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, to='comisarias.serviciosemergencia'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, to='comisarias.serviciosemergencia'),
        ),
        migrations.AddField(
            model_name='comisariacuarta',
            name='solicitante_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.solicitantecodigo'),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='solicitante_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.solicitantecodigo'),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='solicitante_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.solicitantecodigo'),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='solicitante_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.solicitantecodigo'),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='solicitante_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisarias.solicitantecodigo'),
        ),
    ]
