# Generated by Django 5.0.6 on 2024-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0007_alter_comisariacuarta_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
