# Generated by Django 5.0.6 on 2024-08-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0008_dependenciasmunicipales_dependenciasprovinciales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDependenciaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comisaria_cuarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_municipal', to='comisarias.comisariacuarta')),
                ('comisaria_primera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_municipal', to='comisarias.comisariaprimera')),
                ('comisaria_quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_municipal', to='comisarias.comisariaquinta')),
                ('comisaria_segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_municipal', to='comisarias.comisariasegunda')),
                ('comisaria_tercera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_municipal', to='comisarias.comisariatercera')),
                ('dependencia_municipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisarias.dependenciasmunicipales')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDependenciaProvincial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comisaria_cuarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_provincial', to='comisarias.comisariacuarta')),
                ('comisaria_primera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_provincial', to='comisarias.comisariaprimera')),
                ('comisaria_quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_provincial', to='comisarias.comisariaquinta')),
                ('comisaria_segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_provincial', to='comisarias.comisariasegunda')),
                ('comisaria_tercera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dependencia_provincial', to='comisarias.comisariatercera')),
                ('dependencia_provincial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisarias.dependenciasprovinciales')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInstitucionHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comisaria_cuarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_hospitalaria', to='comisarias.comisariacuarta')),
                ('comisaria_primera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_hospitalaria', to='comisarias.comisariaprimera')),
                ('comisaria_quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_hospitalaria', to='comisarias.comisariaquinta')),
                ('comisaria_segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_hospitalaria', to='comisarias.comisariasegunda')),
                ('comisaria_tercera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_institucion_hospitalaria', to='comisarias.comisariatercera')),
                ('institucion_hospitalaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisarias.institucioneshospitalarias')),
            ],
        ),
    ]
