# Generated by Django 5.0.6 on 2024-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisarias', '0009_remove_comisariacuarta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisariacuarta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaprimera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariaquinta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariasegunda',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comisariatercera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comisariacuarta',
            name='a_cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariacuarta',
            name='movil_patrulla',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariacuarta',
            name='secundante',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='a_cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='movil_patrulla',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaprimera',
            name='secundante',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='a_cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='movil_patrulla',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariaquinta',
            name='secundante',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='a_cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='movil_patrulla',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariasegunda',
            name='secundante',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='a_cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='movil_patrulla',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comisariatercera',
            name='secundante',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
