# Generated by Django 5.0.6 on 2024-07-27 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncargadoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionComunicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_guardia', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizacion_guardia', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=255)),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('movil_patrulla', models.CharField(max_length=255)),
                ('personal_cargo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('intervencion_comisaria', models.CharField(max_length=255)),
                ('encargado_guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisioncomunicaciones.encargadoguardia')),
                ('personal_guardia', models.ManyToManyField(to='divisioncomunicaciones.personalguardia')),
            ],
        ),
    ]
