# Generated by Django 5.0.6 on 2024-09-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisioncomunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuartoGuardiaUSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuarto', models.CharField(max_length=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='intervencion_comisaria',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='movil_patrulla',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='personal_cargo',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='divisioncomunicaciones',
            name='telefono',
        ),
        migrations.AddField(
            model_name='divisioncomunicaciones',
            name='distribucion_personal_moviles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisioncomunicaciones',
            name='novedades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisioncomunicaciones',
            name='oficial_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encargadoguardia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalguardia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='divisioncomunicaciones',
            name='encargado_guardia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisioncomunicaciones.encargadoguardia'),
        ),
        migrations.AlterField(
            model_name='divisioncomunicaciones',
            name='finalizacion_guardia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divisioncomunicaciones',
            name='inicio_guardia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divisioncomunicaciones',
            name='personal_guardia',
            field=models.ManyToManyField(blank=True, related_name='comunicaciones_guardia', to='divisioncomunicaciones.personalguardia'),
        ),
        migrations.AlterField(
            model_name='encargadoguardia',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalguardia',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='divisioncomunicaciones',
            name='cuarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divisioncomunicaciones.cuartoguardiaush'),
        ),
        migrations.CreateModel(
            name='EventoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(blank=True, choices=[('PRESENTE', 'Presente'), ('INICIA', 'Inicia'), ('FINALIZA', 'Finaliza'), ('SE_RETIRA', 'Se Retira'), ('CONSTANCIA', 'Constancia')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_evento', models.DateTimeField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='divisioncomunicaciones.divisioncomunicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGuardiaBis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eventobis', models.CharField(blank=True, choices=[('ENCARGADO DE GUARDIA', 'Encargado de Guardia'), ('OPERADOR Y LIBRO DE GUARDIA', 'Operador y Librero'), ('CONSIGNA', 'Consigna'), ('PUESTO LLAVERO', 'Puesto llavero')], max_length=50, null=True)),
                ('nombre_jerarquia', models.CharField(blank=True, max_length=255, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventosbis', to='divisioncomunicaciones.divisioncomunicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGuardiaBisUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eventobisuno', models.CharField(blank=True, choices=[('MOVIL', 'Movil'), ('PATRULLA', 'Patrulla')], max_length=50, null=True)),
                ('movil_patrulla', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_jerarquia_movil_patrulla', models.TextField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventosbisuno', to='divisioncomunicaciones.divisioncomunicaciones')),
            ],
        ),
    ]
