# Generated by Django 5.0.6 on 2024-09-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartido', '0001_initial'),
        ('divisioncomunicaciones', '0002_cuartoguardiaush_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisioncomunicaciones',
            name='cuarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compartido.cuartoguardiaush'),
        ),
        migrations.DeleteModel(
            name='CuartoGuardiaUSH',
        ),
    ]
